/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.jdesktop.j3d.loaders.vrml97.impl;

public interface ParserConstants {

  int EOF = 0;
  int COMMENT = 7;
  int NUMBER_LITERAL = 8;
  int STRING_LITERAL = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int LBRACKET = 12;
  int RBRACKET = 13;
  int TRUE_UC_LITERAL = 14;
  int TRUE_LC_LITERAL = 15;
  int FALSE_UC_LITERAL = 16;
  int FALSE_LC_LITERAL = 17;
  int DEF = 18;
  int USE = 19;
  int PROTO = 20;
  int EVENTIN = 21;
  int EVENTOUT = 22;
  int FIELD = 23;
  int EXPOSEDFIELD = 24;
  int EXTERNPROTO = 25;
  int ROUTE = 26;
  int TO = 27;
  int NULL = 28;
  int IS = 29;
  int DOT = 30;
  int SFBOOL = 31;
  int SFCOLOR = 32;
  int SFFLOAT = 33;
  int SFINT32 = 34;
  int SFNODE = 35;
  int SFROTATION = 36;
  int SFSTRING = 37;
  int SFTIME = 38;
  int SFVEC2F = 39;
  int SFVEC3F = 40;
  int MFCOLOR = 41;
  int MFFLOAT = 42;
  int MFINT32 = 43;
  int MFNODE = 44;
  int MFROTATION = 45;
  int MFSTRING = 46;
  int MFTIME = 47;
  int MFVEC2F = 48;
  int MFVEC3F = 49;
  int ID = 50;
  int ID_FIRST = 51;
  int ID_REST = 52;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\",\"",
    "<COMMENT>",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"TRUE\"",
    "\"true\"",
    "\"FALSE\"",
    "\"false\"",
    "\"DEF\"",
    "\"USE\"",
    "\"PROTO\"",
    "\"eventIn\"",
    "\"eventOut\"",
    "\"field\"",
    "\"exposedField\"",
    "\"EXTERNPROTO\"",
    "\"ROUTE\"",
    "\"TO\"",
    "\"NULL\"",
    "\"IS\"",
    "\".\"",
    "\"SFBool\"",
    "\"SFColor\"",
    "\"SFFloat\"",
    "\"SFInt32\"",
    "\"SFNode\"",
    "\"SFRotation\"",
    "\"SFString\"",
    "\"SFTime\"",
    "\"SFVec2f\"",
    "\"SFVec3f\"",
    "\"MFColor\"",
    "\"MFFloat\"",
    "\"MFInt32\"",
    "\"MFNode\"",
    "\"MFRotation\"",
    "\"MFString\"",
    "\"MFTime\"",
    "\"MFVec2f\"",
    "\"MFVec3f\"",
    "<ID>",
    "<ID_FIRST>",
    "<ID_REST>",
  };

}
